name: docker-image

on:
  push:
  schedule:
    - cron: '0 0 1 * *'  # run once-a-month

jobs:
  docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Pull marijanbeg/bloch_point:finmag
      run: docker pull marijanbeg/bloch_point:finmag

    - name: Run simple command in marijanbeg/bloch_point:finmag
      run: docker run marijanbeg/bloch_point:finmag bash -c "python -c \"import finmag\""
