name: docker-image

on:
  push:
  schedule:
    - cron: '0 0 1 * *'  # run once-a-month

jobs:
  docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Initialisation
      uses: actions/checkout@v2

    - name: Pull docker image
      run: docker pull marijanbeg/bloch_point:finmag

    - name: Run simple command
      run: docker run -ti marijanbeg/bloch_point:finmag bash -c "python -c \"import finmag\""
