name: docker-image

on:
  push:
  schedule:
    - cron: '0 0 1 * *'  # run once-a-month

jobs:
  workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Initialisation
      uses: actions/checkout@v2

    - name: Pull docker image
      run: docker pull marijanbeg/bloch_point:finmag
